### PR TITLE
Add some commands to troubleshoot

### PR DESCRIPTION
**Pull request by sydoluciani**

### CODE REVIEW

**Comment by stevepiercy** [comment]
I cancelled the latest workflow as it appeared to have hung on `tox -e functional3` after about 5 minutes.

**Comment by stevepiercy** [comment]
BTW, I use [this page to get all the Actions in a list](https://github.com/Pylons/deform/actions), reloading after each push, and opening the specific job in a new tab to monitor its progress. It also shows immediate failures that do not show up in the PR page.

**Comment by sydoluciani** [comment]
> I cancelled the latest workflow as it appeared to have hung on `tox -e functional3` after about 5 minutes.

I have added DISPLAY environment variable to GHA global environment in [here](https://github.com/Pylons/deform/pull/494/commits/e67217c7472cb56f81a167ea59f0212f8714ff2b#diff-03609cb60b0c6e92fb771eb8787d6722b8c31ca4c03eabc788e147acd8c6fb43), however the check in deformdemo in [here](https://github.com/Pylons/deformdemo/blob/master/deformdemo/test.py#L351-L355) didn't print out in workflow output, so I am not sure if the sudden exit is the cause of hang, or other problems, so added an else statement to see if DISPLAY is set. if yes, then there are other variables needs to be checked. please merge latest deformdemo pull request that contains the else clause to print DISPLAY number.

**Comment by sydoluciani** [comment]
To import TOX environment variables to GHA, add equivalant of [this line](https://github.com/Pylons/deform/blob/master/.travis.yml#L31) in [here](https://github.com/Pylons/deform/pull/494/commits/e67217c7472cb56f81a167ea59f0212f8714ff2b#diff-03609cb60b0c6e92fb771eb8787d6722b8c31ca4c03eabc788e147acd8c6fb43R15) but not sure if it is correct. we dont

**Comment by stevepiercy** [comment]
I [merged the deformdemo branch](https://github.com/Pylons/deformdemo/pull/95), then [restarted the build here in Deform](https://github.com/Pylons/deform/runs/1372852976?check_suite_focus=true). It partly fails and appears to still stall on functional3 tests.

**Comment by stevepiercy** [comment]
Hey, it looks like you got it! The functional tests just don't provide any feedback until exit. I pushed a fix for the matrix to your branch.

**Comment by stevepiercy** [comment]
To follow up on those suggestions from Keybase:

## Suggestion 1
```
    - name: Install webdriver
      run: |
        sudo apt-get update
        sudo apt-get -yqq install firefox firefox-geckodriver
```

firefox is already installed in ubuntu, but it doesn't hurt to specify it and ensures that it does get installed in case it gets removed in a future release.

## Suggestion 2

> Instead you'll want to grab a docker image and run the whole stack using docker-compose to run all the tests.
> 
> For example: https://hub.docker.com/r/selenium/standalone-firefox
> 
> The nice thing is that you'll be able to use the same docker-compose setup to run tests locally as well.

This one looks interesting and worth a separate branch for trying out.

**Comment by stevepiercy** [comment]
Suggestion 1 was successful!

I'm going to try a couple more things to see if they are really necessary.

**Comment by stevepiercy** [comment]
Tip: I just discovered that GHA will run all actions in the queue, unlike Travis and Appveyor. You can push a series of commits, and they will all run simultaneously.

**Comment by stevepiercy** [comment]
I'm going to merge this PR, then let the parent PR sit for a while before merging to master. I want to try out the docker option on a separate branch.

**Comment by stevepiercy** [comment]
Thank you for your work on this @sydoluciani.

I don't know much about the docker option from [Suggestion 2 above](https://github.com/Pylons/deform/pull/494#issuecomment-723846706), but I'll take a look tomorrow.

**Comment by sydoluciani** [comment]
> Thank you for your work on this @sydoluciani.
> 
> I don't know much about the docker option from [Suggestion 2 above](https://github.com/Pylons/deform/pull/494#issuecomment-723846706), but I'll take a look tomorrow.

@stevepiercy it took us two days to figure it out, but now I know Github Actions, thank you :smile: 

We considerably did lots of commits to troubleshoot different senarios, are you going to rebase and remove those tests or you are going to create a new pull request to eliminate those unnecessary commits from history of commits and reduce the pollutions ?

I am going to check starting a container from within Github Actions some time today evening, will let you know if I have any progress.

**Comment by stevepiercy** [comment]
I can do a squash commit on merge.

Screen Shot 2020-11-09 at 12 19 32 PM

I have a few more commits to push to my PR, then I'll merge it. The Pyramid maintainers made some improvements to [coverage on the 1.10-branch](https://github.com/Pylons/pyramid/pull/3630/files#diff-03609cb60b0c6e92fb771eb8787d6722b8c31ca4c03eabc788e147acd8c6fb43R58-R74). I also want to backport this to the 2.0-branch.

Thanks for picking up the Docker container experiment!

**Pull request merged**
