### PR TITLE
Add placeholder support for Text Area widget.

### PR DESCRIPTION
**Pull request by suzil**
refs #343

### CODE REVIEW

**Comment by suzil** [comment]
No more error now!

**Comment by karantan** [comment]
This can probably be merged now right?

**Comment by tisdall** [comment]
#345 might make more sense to support other attributes.  However, that PR doesn't have tests, signed contributors, docs, etc.

**Comment by karantan** [comment]
>  However, that PR doesn't have tests, signed contributors, docs, etc.

True. I'll ping suzil to fix this.

**Comment by tisdall** [comment]
> True. I'll ping suzil to fix this.

The PR without the tests, etc is #345 .  This one has all that but only supports `placeholder` on the `textarea` widget.  I'm suggesting #345 would be a better PR to use, but it's lacking the components necessary for a merge.

**Pull request closed without merging**
