### PR TITLE
Add Swahili Translations for sw_KE Locale

### PR DESCRIPTION
**Pull request by ooduor**
Initial LC_MESSAGES for Swahili l10n

### CODE REVIEW

**Comment by stevepiercy** [comment]
@ooduor thank you for your pull request. Would you please update [CONTRIBUTORS.txt](https://github.com/Pylons/deform/blob/master/CONTRIBUTORS.txt) by adding your name and date to the end of the file, and pushing that to your pull request?

We also need to resolve some issues unrelated to you pull request so that the Travis build succeeds. Once we resolve those issues, then we can merge the PR.

**Comment by ooduor** [comment]
@stevepiercy I have now included the updated CONTRIBUTORS.txt to my pull request. Thank you!

**Comment by stevepiercy** [comment]
Thank you @ooduor. I've fixed one of the build issues for docs, and I have time to work on the remaining 3 builds today.

**Comment by stevepiercy** [comment]
@ooduor would you please rebase your PR on master, and push it? That should resolve both the build failures and the merge conflict in `CONTRIBUTORS.txt`. Thank you!

**Comment by ooduor** [comment]
@stevepiercy Rebased and seems `contributors.txt` still has conflict with main branch which seems ahead now. I'm not sure of next steps to resolve this but I could re-do and make another pull request from current main. Unless there are quicker ways to resolve it.

**Comment by stevepiercy** [comment]
@ooduor it looks like you did not actually resolve the merge conflict when you rebased on master, but perhaps just marked it as resolved? Whatever is easier for you, I will accept. Thank you!

**Pull request closed without merging**
