### PR TITLE
Improve section for Chrome.

### PR DESCRIPTION
**Pull request by stevepiercy**
- Add command to remove webdriver from macOS quarantine.
- Bump geckodriver version.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@sydoluciani @tdamsma if you want to try out Chrome, I added instructions for macOS. I did this in a failed attempt to determine why the select2sortable plugin could not be controlled via Selenium, and this is my write up from my notes.

If you have additions for your OS, I'll accept them! Feedback appreciated.

**Comment by stevepiercy** [comment]
Note that I got `Ran 239 tests in 478.777s, FAILED (errors=8, failures=9)`, but that means 222 successes! 😁

**Comment by sydoluciani** [comment]
> Note that I got `Ran 239 tests in 478.777s, FAILED (errors=8, failures=9)`, but that means 222 successes! 😁

I tried latest "stand alone selenium chrome container" and got 6 errors, downgraded to lower version , and got 2 errors.
Either we can replace the [local dirver](https://github.com/Pylons/deformdemo/blob/master/deformdemo/test.py#L260) with container version, or we can have local driver and container both. 

Firefox will be the main stream that shall pass either local driver or container, the rest will be experimental.

**Comment by stevepiercy** [comment]
> Either we can replace the local dirver with container version, or we can have local driver and container both.

Yeah, that will come in the next iteration to go with your PR. I want to at least have this part done, so I'm merging for now.

**Pull request merged**
