### PR TITLE
Added html attributes support (e.g. including placeholder and maxlength)

### PR DESCRIPTION
**Pull request by magoarcano**
I added to the templates, inside tal:attributes, the following:

`attributes|field.widget.attributes|{};`

So now it's possible to define a widget like:
`my_field = colander.SchemaNode(colander.Integer(), widget=TextInputWidget(attributes={'maxlength': 8, 'placeholder': 'nickname', 'disabled': True}))`

For some widgets like checked_input or checked_password, you can add attributes to individually to each input using the parameters `attributes` and `confirm_attributes`.

The same way with date_parts (using `year_attributes`, `month_attributes` and `day_attributes` parameters).
And the same with datetime input (using `year_attributes` and `time_attributes` parameters)

It resolves https://github.com/Pylons/deform/pull/116 issue, and requests in that conversation: adding `required`, `maxlength` or `placeholder` attributes,  `data-*` attributes.

It also resolves the following issue, quoted from that conversation:
```
@tilgovi For what it's worth, I should clarify that my thoughts are that all attributes (including those that exist as class attributes already: eg size, class, style etc) for Deform would benefit from being defined in a 2-tuple manner.

At present, if you want to add any new attribute (not just data-*), you end up needing to customise and re-define all these attributes on both your Widget class and in your template. Maintaining sets of copies of the templates just because I need to add an attribute (eg data-*, tabindex, autocomplete or anything else) is overly complicated.
```

### CODE REVIEW

**Comment by Themanwithoutaplan** [comment]
I don't see any tests.

**Comment by stevepiercy** [comment]
@magoarcano thanks for this. There are a few housekeeping chores:

1. Please sign [CONTRIBUTORS.txt](https://github.com/Pylons/deform/blob/master/CONTRIBUTORS.txt) by appending your name and date to the file, and pushing the commit to this PR.
2. If the code is acceptable, I think it would be good to add some tests for this. @miohtama the maintainer can provide better guidance or direction, or you can find examples in https://github.com/Pylons/deform/tree/master/deform/tests.
3. Similar to 2., I would like to see updated documentation that describes the new feature.

**Comment by tseaver** [comment]
FWIW, these are template-only changes, which means that tests would go in `test_functional.py`.

**Comment by JanLikar** [comment]
@magoarcano Could you please sign https://github.com/Pylons/deform/blob/master/CONTRIBUTORS.txt? I'm willing to write the missing tests because we really need this functionality but the PR won't get merged, unless you sign it.

**Comment by ericof** [comment]
@stevepiercy: I will merge this PR and write the functional tests

**Pull request merged**
