### PR TITLE
[WIP] Add HTML5 attributes to buttons

### PR DESCRIPTION
**Pull request by stevepiercy**
DO NOT MERGE.

See #389

### CODE REVIEW

**Comment by stevepiercy** [comment]
I need some help with getting the Travis-CI to run successfully.

It appears that since the last time `master` was [built successfully 11 months ago](https://travis-ci.org/Pylons/deform/builds/455046509), something has changed with Travis-CI that [now causes `master` builds to fail for py37 and py38](https://travis-ci.org/Pylons/deform/jobs/455067766#L220):

```
The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .
```

On every version of Python, this PR fails.

Once I get over that problem, then I'll write a test for this feature.

**Comment by stevepiercy** [comment]
Little more digging. From https://github.com/Pylons/deform/blob/master/.travis.yml#L46-L51

```
# For Selenium
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
# http://stackoverflow.com/a/34703838/315168
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
```

This is way over my head.

When I look at each of the failures, it looks like Xenial is used for all platforms. Help!

**Comment by ericof** [comment]
@stevepiercy Help is coming, I will look into it in the next few days.

**Comment by bertjwregeer** [comment]
@stevepiercy https://benlimmer.com/2019/01/14/travis-ci-xvfb/

**Comment by stevepiercy** [comment]
@bertjwregeer DuckDuckFu is strong in you. That got me over the first hurdle.

I'm working on fixing the [failing functional test](https://travis-ci.org/Pylons/deform/jobs/590932987#L422).

@ericof Looking ahead, what can I do to help cut a release for deform? Do I need to do anything in deformdemo, too?

**Comment by stevepiercy** [comment]
This PR has nothing to do with the [failing test in deformdemo](https://github.com/Pylons/deformdemo/blob/master/deformdemo/test.py#L2112). When I manually simulate the failing test code by running deformdemo locally and clicking per the steps in this test method, I verified that all the necessary `id`s and texts show up. I don't understand why the automated test fails.

Perhaps the form submission takes longer to render the error message in `error-deformField3` than the step `wait_to_click` allows? The test code seems to handle this situation, so I'm at a loss what else to try next.

**Comment by stevepiercy** [comment]
@ericof do you have any suggestion for how to fix the one failing functional test? I am stumped.

**Comment by ericof** [comment]
@stevepiercy I've been trying to reproduce it locally as well.

**Comment by stevepiercy** [comment]
@ericof how about merging this PR and cutting a release, since the failing test is not related to this PR? Then we can open a new issue for the failing test.

Meanwhile what do you do locally to run the test? I couldn't figure out any other method than running the deformdemo and manually clicking through it in a web browser. If I try an automated method, maybe I can spot the problem.

**Comment by ericof** [comment]
Merging and fixing the test after the release

**Pull request merged**
