### PR TITLE
Added Simplified Chinese translations

### PR DESCRIPTION
**Pull request by rikuayanokozy**

### CODE REVIEW

**Comment by tisdall** [comment]
shouldn't the locale code be "zh_CN"?

**Comment by tisdall** [comment]
okay, after some Google searches it seems "zh_hans" is more "proper", but I'm wondering which one actually works in practice...  ^_^

**Comment by rikuayanokozy** [comment]
According [RFC4646] (http://www.ietf.org/rfc/rfc4646.txt), an language code should be {language-script-region-variant-extension-privateuse}.
The language code "zh-CN" will be grandfathered in future.
But many system using language code "zh-CN" , should we made a copy as "zh-CN"?

**Comment by rikuayanokozy** [comment]
In the latest commit, I copied zh-Hans and change language code to zh-CN.

**Comment by tisdall** [comment]
Is the only way to support both codes duplicating the files?

**Comment by rikuayanokozy** [comment]
It's depends on the "caller of gettext" internal implements, is the only way to support both under the [Pyramid official localizer implements] (https://github.com/Pylons/pyramid/blob/6e0f02a1e2d6fdece760f5ce1e61850b9514897d/pyramid/i18n.py#L169).

**Comment by miohtama** [comment]
Thank you for your pull request.

I am the new Deform project maintainer. I apologize the issue of this pull request not being commented earlier. Deform project is again under activate maintenance.

This is issue tracker / pull request clean to prepare a new release.

As I don't see any roadblockers on this merge, I merge this pull request.

**Pull request merged**
