### PR TITLE
i18n clean up/update

### PR DESCRIPTION
**Pull request by frispete**

### CODE REVIEW

**Comment by miohtama** [comment]
Holy moly @frispete you are awesome

**Comment by frispete** [comment]
Thanks, Mikko, just beginning ;)

Any idea, what travis is stumbling on here?

**Comment by miohtama** [comment]
There are tests for i18n and they fail with this patch. E.g.

```
======================================================================

FAIL: test_submit_empty_ru (deformdemo.test.InternationalizationTests)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/Pylons/deform/deformdemo_functional_tests/deformdemo/test.py", line 1459, in test_submit_empty_ru

    u'Данные которые вы предоставили содержат ошибку')

AssertionError: u'There was a problem with your submission' != u'\u0414\u0430\u043d\u043d\u044b\u0435 \u043a\u043e\u0442\u043e\u0440\u044b\u043 [truncated]...

- There was a problem with your submission

+ \u0414\u0430\u043d\u043d\u044b\u0435 \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0432\u044b \u043f\u0440\u0435\u0434\u043e\u0441\u0442\u0430\u0432\u0438\u043b\u0438 \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u0442 \u043e\u0448\u0438\u0431\u043a\u0443
```

**Comment by frispete** [comment]
Yes, they fail because translation of python strings doesn't work at all at the moment.

You may want to chime in the discussion @pylons-devel mailing list, where I reported the problem, not knowing, if it's a pyramid, translationstring, deform, deformdemo or anything else's problem is...

The problem is most certainly not related to this patch, since the relevant code changes are in first patch only.

**Comment by miohtama** [comment]
@frispete looks like my last updates to deformdemo might have broken this. It was not caught by automated tests, because the tests run across two different repos. Let me try to restore the master to a working state tonight or tomorrow.

**Comment by miohtama** [comment]
I confirmed this by rerunninng the latest green deform commit on Travis. It was working before, now goes red.

**Comment by frispete** [comment]
Hey @miohtama please check out my fixes for deformdemo. It's working again and should fix the travis issues here as well!

**Comment by frispete** [comment]
Hi @miohtama, now that you merged my fixes to deformdemo, can you trigger travis run here please, I expect it to succeed..

**Comment by bertjwregeer** [comment]
Kicked and success :D

**Comment by miohtama** [comment]
This is actually already merged. Somehow github did not notice it. Let me see.

**Comment by miohtama** [comment]
Wait, I mixed up PR on deformdemo and this one.

**Comment by frispete** [comment]
Hmm, with PR of deformdemo and this one in place, the dialog text [here](http://deformdemo.repoze.org/i18n/?_LOCALE_=nl) should appear in dutch, but does not :(...

**Pull request merged**
