### PR TITLE
Add traditional chinese localization

### PR DESCRIPTION
**Pull request by dwt**
Hi there,

we got this translation from one of our users in Taiwan who complained about simplified Chinese characters in the app.

Now I'm not speaking any Chinese so it is kind of hard for me to judge this (or wether you would want to take this in).

However, I can offer some observations: It looks like `zh` (the base translation) already has traditional Chinese characters. This is, to my understanding, a bit odd, as zh (without script qualifier) should probably be simplified Chinese, as that is used by the vast majority of Chinese readers. (i.e. it should probably symlink to zh_Hans? Or maybe zh_Hans is just moved to zh_Hant?)

For us the most important part is that a request for zh_Hant actually returns traditional chinese characters (which it seems to not have in the past) -> which is why we provide this pull request.

### CODE REVIEW

**Comment by tisdall** [comment]
I'm not really sure which language codes are supposed to be used, but there are differences between Taiwan and Hong Kong which both use traditional.  The differences are similar to differences between UK English and US English.  Taiwan is usually denoted with "zh_TW" or something like that.  Again, I'm not sure which locale encoding is used for these files.

There seems to already be "zh", "zh_CN", and "zh_Hans" in the repo.

**Comment by dwt** [comment]
To my understanding how these language codes work, it is best to have zh_Hant that is used for both Taiwan and Hongkong until you get translations that are specialized for the two.

**Comment by dwt** [comment]
My Guess is, that zh_CN is probably simplified chinese and zh is probably traditional chinese characters. My understanding is that you probably want to rename zh_CN -> zh_Hans or zh, zh -> zh_Hant (or take our translation, a native speaker would have to decide).

Perhaps it is even best to rename zh -> zh_Hant_HK and zh_Hant (ours) to zh_Hant_TW - but that really depends on where that translation comes from - which only a native speaker can confirm.

**Comment by rbu** [comment]
@tisdall, please note that "Hant" and "Hans" are script subtags whereas "CN" and "TW" are region subtags. Unless you actually have a specific localisation file for Taiwan or Hong Kong, just use "zh_Hant" for a Chinese translation in Traditional script (even if it's made by a Hong Kong or Taiwan speaker).

**Comment by tisdall** [comment]
So, it seems like we should clean things up and just have zh_Hans and zh_Hant?  If someone just requested a "zh" language it's valid to return either, right?  It seems like this PR is fine to accept and then someone needs to merge the 3 other existing (zh, zh_Hans, zh_CN) into a single zh_Hans file.

BTW, this .po file mentions the same translator as other files in the repo...  was that just cut-n-copied over or is it the same translator?

**Comment by dwt** [comment]
Sorry, that was a copy paste error I guess. Should I change the PR?

**Comment by dwt** [comment]
I would agree that just having zh_Hans and zh_Hant is the right way to go. If someone just requests zh it is probably the best bet to return zh_Hans as that is (to my understanding) read by more people.

**Comment by tisdall** [comment]
@dwt - I think it'd be a good idea to remove or change the translator so that person doesn't get contacted regarding work they didn't do.  ;)

I think it's legit to just return either language if someone just requests for "zh".  I'd say anyone requesting Chinese, though, will have it set to request a more specific language like "zh_CN" or "zh_Hans" unless they really can read either format.  (I'm assuming it's the same as en_US and en_UK if a user requests "en"...  they'll get one or the other but there's no right answer as to which they receive.)  Either way, that's a problem for Pyramid or something else handling language negotiation and not deform, the major concern here is to remove duplication and have only zh_Hans and zh_Hant.

BTW, while you're editing the file, I think you should make a note in the file that the translator provided a Taiwanese translation.  That way English speakers can identify which specific variant of zh_Hant they're dealing with.

**Comment by dwt** [comment]
Here you go. :)

**Comment by dwt** [comment]
ping @maintianers: Is there anything you need to merge this?

**Comment by tisdall** [comment]
@miohtama see Pylons/colander#285

**Comment by dwt** [comment]
ping @maintainers…

**Comment by miohtama** [comment]
Maintainers are here. Been busy, waiting for the next sprint and merge fest!

**Comment by tisdall** [comment]
@dwt - btw, you're pinging the maintainers of github with that...  I think the maintainers of this project get a notification any time anything is posted regardless of tagging.

**Pull request merged**
