### PR TITLE
Add GitHub Actions for matrix of Pythons and OSes, coverage, docs, an…

### PR DESCRIPTION
**Pull request by stevepiercy**
…d lint

- TODO: functional3 browser tests

### CODE REVIEW

**Comment by stevepiercy** [comment]
@sydoluciani I'm flailing and have no idea how to get the functional web tests to run in GitHub Actions. All the other jobs succeed. I'm going to keep making random guesses until something works, but if you have any clue, I sure would appreciate it.

**Comment by sydoluciani** [comment]
> @sydoluciani I'm flailing and have no idea how to get the functional web tests to run in GitHub Actions. All the other jobs succeed. I'm going to keep making random guesses until something works, but if you have any clue, I sure would appreciate it.

I am going to start working on it tomorrow. 
this would be my first time working with Github Actions, so it might take a bit of time.
What is the benefit of moving from Travis-ci to Github Actions ?
I guess every one is going to migrate.

**Comment by sydoluciani** [comment]
@stevepiercy, with a quick look at log files, and comparing travis.yml and .github/workflows/ci-tests.yml, I think we are missing [this directive in travis.yml](https://github.com/Pylons/deform/blob/master/.travis.yml#L4-L5) in ci-tests.yml.

That directive in travis.yml adds Firefox to container. 
Either we should install Firefox using apt-get, or finding the equivalant in Github action to add that service to container. 

You can place an echo command, to make sure Firefox is installed and it is in path.

**Comment by sydoluciani** [comment]
Please add ``` firefox``` to this line [line](https://github.com/Pylons/deform/blob/github-actions/.github/workflows/ci-tests.yml#L72) and test.

**Comment by sydoluciani** [comment]
And we are missing [this service](https://github.com/Pylons/deform/blob/master/.travis.yml#L7-L8) as well.

[Here](https://github.com/juliangruber/browser-run/issues/147) is the example to set Xvfb.

```
export DISPLAY=:99
Xvfb :99 &

```

**Comment by stevepiercy** [comment]
Travis has severely restricted queueing on .org, increasing build times to several hours. It then limits OSS to 10,000 minutes of build time on .com, which most orgs will burn through during heavy usage such as releases and sprints. GHA has none of that nonsense for OSS. There is a [discussion over in the Plone community](https://community.plone.org/t/travis-ci-org-shuts-down-dec-31st/13055) where more details are available to verify. It's worth a read.

I'll make these changes and push in an hour or so. Although @sydoluciani you should be able to push commits to this branch. If not, please let me know. Thank you!

**Comment by sydoluciani** [comment]
@stevepiercy Tried it and failed again, trying again, will let you know if figured it out.

Do you have to merge it to run the test against my pull request ?
If not, I am ok with the way it is, but if you have to merge to run the test , then I guess having access making it easier.
I am trying to find out what is the problem and it might take a bit of time.

Plone seems to moving forward pretty good, how come plone didn't come under the Pyramid umbrella ?
I was sad seeing their react frontend Volto not working with Plone and not Pyramid, planning to join to see how we can get support for Pyramid or how we can add Volto like to Pyramid.

**Comment by sydoluciani** [comment]
@stevepiercy I think the way it is now, is better, I am going to remove all tests and only have the functional3 on this pull request, once figured it out, then you can only add the difference to your pull request. no need to run all tests when we are only working on functional3.

**Comment by stevepiercy** [comment]
@sydoluciani a PR against this branch will run GHA. Either way is fine, as long as you rebase your branch on this branch whenever I push new commits to this branch. I'll leave it alone for a while to give you some time to attempt a fix. Please let me know when you would like me to take the reins.

As far as Plone/Zope/Pylons, that's a long story. Briefly they all share a common root, but branched out in different directions. Now the organizations have begun to recombine. Zope is now under the Plone Foundation. Pylons Project has engaged in discussions to consider moving under the Plone Foundation. Pylons Project has no legal entity for collecting or disbursing funds and other organizational benefits, which is the primary motivation for us to seek such an entity.

**Comment by sydoluciani** [comment]
@stevepiercy somehow DISPLAY environment variable is not being set with normal shell command ``` - run: export DISPLAY=:99``` and  firefox won't start with error message DISPLAY envrionment variable is not set. using different method in setting environment varialbe:
  ```
- env: 
                DISPLAY: 99
```

but tests are not being run any more, is there any restriction in running number of tests ?

**Comment by sydoluciani** [comment]
@stevepiercy  My mistake, wrong place for env directive, tests started again. sill learning Github Action.

**Comment by stevepiercy** [comment]
I made many similar mistakes. :wink: We're both learning.

**Comment by sydoluciani** [comment]
Can you please stop this [test](https://github.com/Pylons/deform/pull/494/commits/c95b22320e1a0672fe710fbba8fbf296e69a94f8) forgot to add ampersand after firefox and now test is stuck after firefox started.

We added this [line](https://github.com/Pylons/deformdemo/blob/master/deformdemo/test.py#L262) to differentiate between TRAVIS environment and local, but now that we are moving to Github Action, we should find an equivalent environment variable in Github Action. working on it.

**Comment by stevepiercy** [comment]
Done! https://github.com/Pylons/deform/runs/1368949761

**Comment by sydoluciani** [comment]
@stevepiercy Thank you, going to have dinner and have some fresh air. 
then I have to do some research to find an equivalanet for this [line](https://github.com/Pylons/deformdemo/blob/master/deformdemo/test.py#L262)
or maybe changing the logic a bit to be able to identify local tests than GHA environment.

will let you know as soon as I figured it out.

**Comment by stevepiercy** [comment]
Based on this [output of nothing](https://github.com/Pylons/deform/runs/1369019766#step:11:8), I think your conclusion about `DISPLAY` not getting set is correct. I came to the realization that something or some things did not get set correctly when I paused my experiments. I'll put together a list of requirements, and then we can run down the list and verify what does and does not get set correctly.

**Comment by stevepiercy** [comment]
@sydoluciani I think I found something. Check this out: https://github.com/Pylons/deform/actions/runs/351953635 I think our concepts are correct, but our syntax and usage are just not quite right. We'll get there. I'll flail around at this until I find the right combination.

**Comment by stevepiercy** [comment]
YES! https://github.com/Pylons/deform/runs/1369554799?check_suite_focus=true#step:4:8

**Comment by stevepiercy** [comment]
It appears that `ubuntu-latest` comes with firefox and xvfb pre-installed.

- https://github.com/Pylons/deform/runs/1369595178?check_suite_focus=true#step:5:17 shows what we ask to install
- [firefox is already the newest version (82.0+build2-0ubuntu0.18.04.1).](https://github.com/Pylons/deform/runs/1369595178?check_suite_focus=true#step:5:35)
- [xvfb is already the newest version (2:1.19.6-1ubuntu4.7).](https://github.com/Pylons/deform/runs/1369595178?check_suite_focus=true#step:5:36)

Right now it gets hung up on starting xvfb. I tried both with and without `sudo`. I have seen posts where it is installed as a service. More searching and reading to do.

**Comment by stevepiercy** [comment]
Aha! [`xvfb-run`](https://github.com/Pylons/deform/runs/1369624691?check_suite_focus=true#step:5:10) not `xvfb`!

Also discovered that the scope of env vars is limited to only the step in which they are set.

**Comment by stevepiercy** [comment]
I'm not sure whether xvfb or xfvb-run is the correct command, but I think this recent work gets us closer.

**Comment by stevepiercy** [comment]
Some more things to try from the Keybase chat: keybase://chat/pylons#general/397 I'll be away for the next day, but feel free to try them out.

**Pull request merged**
