### PR TITLE
Upgrade the embedded version of pickadate.js

### PR DESCRIPTION
**Pull request by lmctv**
In going from v3.2.2 to v3.5.4 we gain support for the "hiddenName" picker option; this way, we can instantiate the widget as in

``` python
w = deform.widget.DateInputWidget(options={
                              'format': 'dd/mm/yyyy',
                              'selectYears': 10,
                              'selectMonths': True,
                              'formatSubmit': 'yyyy-mm-dd',
                              'hiddenName': True,
                             }
       )
```

This way, the widget can push its contents with the correct name even if the submit format is different from the display format.

### CODE REVIEW

**Comment by lmctv** [comment]
With #221 in, it seems date input got back to working well. I  thnk the hiddenName option should be unconditionally selected, just like formatSubmit.

**Comment by tseaver** [comment]
LGTM

**Comment by tisdall** [comment]
This may fix #219.  It'd be nice to update this to 3.5.6 and then merge it in.

**Comment by tisdall** [comment]
Thanks for the update!

Has this been checked against the selenium tests in https://github.com/Pylons/deformdemo#running-the-demos-selenium-tests ?

**Comment by lmctv** [comment]
Thank you for the pointer to deformdemo test documentation... I'll follow up after the selenium test runtime...

**Comment by lmctv** [comment]
@tisdall: thank you once more for the pointer to deformdemo selenium tests. I've had to make a little change to adapt deformdemo input type expectations, but I think it makes sense.

If this change goes in, we should be able to revert #221 and get custom named date and time input fields.

**Comment by tisdall** [comment]
@lmctv We already have custom named date and time fields...  It's not totally straightforward, but the names aren't actually fixed.  What it does, is create a new named mapping for each datetime entry.  That mapping has a dynamic name.  The contents of the mapping is two fixed named fields named "date" and "time".  Despite the fixed names, `peppercorn` properly interprets the values back into their proper mappings so you can have multiple datetime fields on a page with no issue.

dairiki added a PR to `deformdemo` to show you could use any name:  https://github.com/Pylons/deformdemo/pull/37

**Comment by lmctv** [comment]
Just rebased the whole stuff on latest master.

**Pull request merged**
