### PR TITLE
Added a new "dev" member to extras_require

### PR DESCRIPTION
**Pull request by jhaiduce**
This PR adds a new "dev" member to extras_require which combines the lint, testing, docs, and functional dependencies, plus tox. This allows a developer to install all the python modules required for testing, linting, and generating documentation with the command

    pip install -e ".[dev]"

### CODE REVIEW

**Comment by jhaiduce** [comment]
Failures on this PR appear to be the result of Travis using Chameleon 3.8.0. Tests on my local machine passed with Chameleon 3.7.2 and failed after upgrading to 3.8.0. Probably related to issue https://github.com/Pylons/deform/issues/417.

**Comment by stevepiercy** [comment]
@jhaiduce yup, test failures are due to a new issue. Pinning requirements to < 3.8.0 is the immediate workaround. We need to figure out a fix going forward.

**Comment by stevepiercy** [comment]
We got a fix coming in, pending passing builds in #418, thanks to slav0nic in IRC.

**Comment by jhaiduce** [comment]
Rebased this PR against master again, hopefully all tests will pass now.

**Comment by bertjwregeer** [comment]
You should only have to install `tox` to be able to run all tests, so far in all of the Pylons projects we have not added any extra's to install `tox`. Installing tox into the same environment where you have also installed `deform` can lead to all kinds of funny testing scenarios do to the way that `PYTHONPATH` is passed through to the underlying processes and you may end up not testing the appropriate code.

I am a huge -1 on this change, but will leave it up to the current maintainers for the project.

**Comment by stevepiercy** [comment]
Thanks, @bertjwregeer. I agree with not installing `tox` this way. I pushed another commit to remove it, and pluralized `functional_testing_extras`. Once it passes build, I can merge it.

Thank you @jhaiduce! This is a really good idea. I will also update the open PR #415 for contributing.md to reflect this change.

**Pull request merged**
